### PR TITLE
Bump build number to 2, add traversaro to mantainers and clarify license

### PR DESCRIPTION
**Pull request by traversaro**
I was debugging some strange package conflict that ended up being caused by:

~~~
traversaro@IITBMP014LW012:~$ conda create -n test "libzlib==1.3.1" zziplib
Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package zziplib-0.13.69-h27826a3_1 requires zlib >=1.2.11,<1.3.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ libzlib 1.3.1  is installable with the potential options
│  ├─ libzlib 1.3.1 would require
│  │  └─ zlib 1.3.1 *_0, which can be installed;
│  └─ libzlib 1.3.1 would require
│     └─ zlib 1.3.1 *_1, which can be installed;
└─ zziplib is not installable because it requires
   └─ zlib >=1.2.11,<1.3.0a0 , which conflicts with any installable versions previously reported.
~~~

Apparently this package has not being built in a long time, and was originally compiled against a version of `zlib` that had some strange `run_exports` constraint. In this PR I rebuild the package, clarify the license and add myself as maintainer.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@wolfv the PR is ready for review, thanks!

**Comment by wolfv** [comment]
Thanks!

**Comment by traversaro** [comment]
Thanks!

**Pull request merged**
